name = "DoingRightNow"
uuid = "e99cb7fb-658f-403b-a4e1-a0d5dc51c961"
authors = ["your-name"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
